import sys
import re

with open('client/src/pages/Report.jsx', 'r', encoding='utf-8') as f:
    content = f.read()

new_handle_export_pdf = """  const handleExportPdf = () => {
    if (!scanData) return;
    
    // Generate massive comprehensive HTML for the PDF
    const htmlContent = `
      <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; line-height: 1.6; max-width: 800px; margin: 0 auto;">
        
        <!-- COVER PAGE -->
        <div style="height: 1000px; padding: 60px; display: flex; flex-direction: column; justify-content: center; text-align: center; border-bottom: 5px solid #000;">
          <h4 style="color: #666; letter-spacing: 2px; text-transform: uppercase;">Confidential Document</h4>
          <h1 style="font-size: 48px; color: #111; margin: 20px 0;">Secura Audit Report</h1>
          <h2 style="font-size: 24px; color: #444; font-weight: 300;">Comprehensive Security Analysis</h2>
          <div style="margin-top: 80px; text-align: left; background: #f9fafb; padding: 40px; border-radius: 12px; border: 1px solid #eee;">
            <p style="margin: 10px 0; font-size: 18px;"><strong>Target Scope:</strong> ${scanData.targetUrl}</p>
            <p style="margin: 10px 0; font-size: 18px;"><strong>Resolved Hostname:</strong> ${scanData.targetHostname}</p>
            <p style="margin: 10px 0; font-size: 18px;"><strong>Date of Assessment:</strong> ${new Date(scanData.scannedAt).toLocaleString()}</p>
            <p style="margin: 10px 0; font-size: 18px;"><strong>Overall Risk Level:</strong> <span style="color: ${scanData.aiReport?.riskLevel === 'HIGH' ? '#dc2626' : scanData.aiReport?.riskLevel === 'MEDIUM' ? '#d97706' : '#16a34a'}">${scanData.aiReport?.riskLevel || 'UNKNOWN'}</span></p>
            <p style="margin: 10px 0; font-size: 18px;"><strong>Security Score:</strong> ${scanData.aiReport?.overallScore || 'N/A'}/100</p>
          </div>
          <p style="margin-top: 100px; font-size: 12px; color: #999;">Generated by Secura Automated Engine v2.0<br/>Do not distribute without authorization.</p>
        </div>

        <!-- PAGE BREAK -->
        <div style="page-break-before: always; padding: 40px;">
          <h2 style="color: #111; border-bottom: 2px solid #000; padding-bottom: 10px; font-size: 28px;">1. Assessment Methodology</h2>
          <p style="font-size: 14px; text-align: justify; margin-bottom: 20px;">
            This security audit was conducted using the Secura AI-powered automated scanning engine. The methodology encompasses a non-intrusive, passive reconnaissance approach designed to identify misconfigurations, outdated software, missing security headers, and known Common Vulnerabilities and Exposures (CVEs) without actively exploiting the target infrastructure.
          </p>
          <p style="font-size: 14px; text-align: justify; margin-bottom: 20px;">
            The assessment phases include:
          </p>
          <ul style="font-size: 14px; margin-bottom: 40px; line-height: 1.8;">
            <li><strong>Surface Diagnostics:</strong> Identification of the technology stack, frameworks, and content management systems.</li>
            <li><strong>Transport Security (SSL/TLS):</strong> Evaluation of cryptographic protocols, certificate validity, and potential deprecation of legacy cipher suites.</li>
            <li><strong>HTTP Security Headers:</strong> Analysis of browser-side security enforcement mechanisms (e.g., CSP, HSTS, X-Frame-Options).</li>
            <li><strong>Nuclei Threat Engine:</strong> Template-based vulnerability scanning against known misconfigurations and exposed sensitive files.</li>
            <li><strong>AI Remediation Engine:</strong> Generative AI analysis of aggregated telemetry to formulate precise, context-aware remediation strategies.</li>
          </ul>

          <h2 style="color: #111; border-bottom: 2px solid #000; padding-bottom: 10px; font-size: 28px;">2. Executive Summary</h2>
          <div style="background: #fff5f5; border-left: 4px solid #ef4444; padding: 20px; margin-bottom: 40px;">
            <p style="font-size: 15px; margin: 0;">${scanData.aiReport?.executiveSummary || 'No summary available.'}</p>
          </div>
        </div>

        <!-- PAGE BREAK -->
        <div style="page-break-before: always; padding: 40px;">
          <h2 style="color: #111; border-bottom: 2px solid #000; padding-bottom: 10px; font-size: 28px;">3. AI Remediation Plan</h2>
          <p style="font-size: 14px; margin-bottom: 20px;">The following vulnerabilities were identified as high priority. The AI engine has provided specific instructions to remediate these risks.</p>
          
          ${scanData.aiReport?.vulnerabilities && scanData.aiReport.vulnerabilities.length > 0 ? 
            scanData.aiReport.vulnerabilities.map(v => 
              `<div style="margin-bottom: 30px; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
                 <div style="background: #f3f4f6; padding: 15px; border-bottom: 1px solid #e5e7eb;">
                   <h3 style="margin: 0; font-size: 18px;">[${v.severity}] ${v.title}</h3>
                 </div>
                 <div style="padding: 15px;">
                   <h4 style="margin: 0 0 5px 0; color: #4b5563; font-size: 14px;">Business Impact:</h4>
                   <p style="margin: 0 0 15px 0; font-size: 14px; color: #111;">${v.impact}</p>
                   <h4 style="margin: 0 0 5px 0; color: #4b5563; font-size: 14px;">Remediation Steps:</h4>
                   <div style="background: #1f2937; color: #f9fafb; padding: 15px; border-radius: 6px; font-family: monospace; font-size: 13px; white-space: pre-wrap;">${v.remediation}</div>
                 </div>
               </div>`
            ).join('')
            : '<div style="background: #f0fdf4; border: 1px solid #bbf7d0; padding: 15px; border-radius: 8px;"><p style="margin:0; color: #166534;">No critical vulnerabilities required AI remediation.</p></div>'
          }
        </div>

        <!-- PAGE BREAK -->
        <div style="page-break-before: always; padding: 40px;">
          <h2 style="color: #111; border-bottom: 2px solid #000; padding-bottom: 10px; font-size: 28px;">4. Nuclei Diagnostic Findings</h2>
          <p style="font-size: 14px; margin-bottom: 20px;">Detailed findings from the Nuclei vulnerability scanner detecting misconfigurations and default credentials.</p>
          
          ${scanData.rawResults?.nuclei && scanData.rawResults.nuclei.length > 0 ? 
            `<table style="width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 40px;">
              <thead>
                <tr style="background: #f8fafc; text-align: left;">
                  <th style="padding: 12px; border: 1px solid #e2e8f0;">Severity</th>
                  <th style="padding: 12px; border: 1px solid #e2e8f0;">Finding Name</th>
                  <th style="padding: 12px; border: 1px solid #e2e8f0;">Description</th>
                </tr>
              </thead>
              <tbody>
                ${scanData.rawResults.nuclei.map(n => 
                  `<tr>
                     <td style="padding: 12px; border: 1px solid #e2e8f0; font-weight: bold; color: ${n.severity === 'critical' ? '#dc2626' : n.severity === 'high' ? '#ea580c' : '#000'}">${n.severity ? n.severity.toUpperCase() : 'INFO'}</td>
                     <td style="padding: 12px; border: 1px solid #e2e8f0;">${n.name || n.info?.name || 'Vulnerability'}</td>
                     <td style="padding: 12px; border: 1px solid #e2e8f0;">${n.description || n.info?.description || 'N/A'}</td>
                   </tr>`
                ).join('')}
              </tbody>
            </table>` 
            : '<p style="font-size: 14px;">No specific Nuclei issues detected during this scan.</p>'
          }

          <h2 style="color: #111; border-bottom: 2px solid #000; padding-bottom: 10px; font-size: 28px; margin-top: 40px;">5. Technology Stack & CVEs</h2>
          ${scanData.rawResults?.cves && scanData.rawResults.cves.length > 0 ? 
            `<div style="font-size: 14px;">
              ${scanData.rawResults.cves.map(tech => 
                `<div style="margin-bottom: 25px;">
                   <h3 style="margin: 0 0 10px 0; font-size: 18px; color: #2563eb;">${tech.name} ${tech.version ? `(Version ${tech.version})` : ''}</h3>
                   ${tech.vulnerabilities && tech.vulnerabilities.length > 0 ? 
                     `<ul style="margin: 0; padding-left: 20px;">
                        ${tech.vulnerabilities.map(vuln => 
                          `<li style="margin-bottom: 8px;"><strong>${vuln.cve}</strong> <span style="background:#fee2e2; color:#991b1b; padding: 2px 6px; border-radius: 4px; font-size: 11px; margin-left: 5px;">${vuln.severity}</span><br/><span style="color: #555;">${vuln.description}</span></li>`
                        ).join('')}
                      </ul>` : '<p style="margin: 0; color: #16a34a; font-weight: 500;">No known CVEs for this technology version.</p>'
                   }
                 </div>`
              ).join('')}
            </div>` : '<p style="font-size: 14px;">No significant tech stack components identified.</p>'
          }
        </div>

        <!-- PAGE BREAK -->
        <div style="page-break-before: always; padding: 40px;">
          <h2 style="color: #111; border-bottom: 2px solid #000; padding-bottom: 10px; font-size: 28px;">6. Protocol & Header Security</h2>
          
          <h3 style="font-size: 20px; color: #333; margin-top: 30px;">SSL / TLS Configuration</h3>
          <table style="width: 100%; border-collapse: collapse; font-size: 14px; margin-bottom: 30px;">
            <tbody>
              <tr>
                <td style="padding: 12px; border: 1px solid #e2e8f0; background: #f8fafc; font-weight: bold; width: 30%;">Certificate Status</td>
                <td style="padding: 12px; border: 1px solid #e2e8f0; color: ${scanData.rawResults?.ssl?.valid ? '#16a34a' : '#dc2626'}">${scanData.rawResults?.ssl?.valid ? 'Valid & Trusted' : 'Invalid / Untrusted'}</td>
              </tr>
              <tr>
                <td style="padding: 12px; border: 1px solid #e2e8f0; background: #f8fafc; font-weight: bold;">Days Remaining</td>
                <td style="padding: 12px; border: 1px solid #e2e8f0;">${scanData.rawResults?.ssl?.daysRemaining || 'N/A'} days</td>
              </tr>
              <tr>
                <td style="padding: 12px; border: 1px solid #e2e8f0; background: #f8fafc; font-weight: bold;">SSL Grade</td>
                <td style="padding: 12px; border: 1px solid #e2e8f0;">${scanData.rawResults?.ssl?.grade || 'N/A'}</td>
              </tr>
              <tr>
                <td style="padding: 12px; border: 1px solid #e2e8f0; background: #f8fafc; font-weight: bold;">Certificate Issuer</td>
                <td style="padding: 12px; border: 1px solid #e2e8f0;">${scanData.rawResults?.ssl?.issuer || 'N/A'}</td>
              </tr>
            </tbody>
          </table>

          <h3 style="font-size: 20px; color: #333; margin-top: 30px;">Missing Security Headers</h3>
          ${scanData.rawResults?.headers?.missing && scanData.rawResults.headers.missing.length > 0 ? 
            `<div style="display: flex; flex-wrap: wrap; gap: 10px;">
              ${scanData.rawResults.headers.missing.map(header => 
                `<span style="background: #fef2f2; color: #b91c1c; border: 1px solid #fecaca; padding: 6px 12px; border-radius: 6px; font-family: monospace; font-size: 13px;">${header}</span>`
              ).join('')}
            </div>
            <p style="font-size: 13px; color: #666; margin-top: 15px;">It is recommended to implement these headers to mitigate XSS, clickjacking, and content-sniffing attacks.</p>` 
            : '<p style="font-size: 14px; color: #16a34a; font-weight: 500;">All required security headers are properly implemented.</p>'
          }

          <div style="margin-top: 80px; padding: 30px; background: #f8fafc; border-radius: 8px; font-size: 12px; color: #64748b; text-align: justify;">
            <strong>Disclaimer:</strong> This automated report is generated for informational purposes only. The findings reflect the state of the target system at the exact time of the scan. Secura does not guarantee that all vulnerabilities have been identified. It is the responsibility of the system owner to manually verify and patch the vulnerabilities before they can be exploited. 
          </div>
        </div>
      </div>
    `;

    // Create a temporary container
    const container = document.createElement('div');
    container.innerHTML = htmlContent;

    const opt = {
      margin: 0,
      filename: `secura_report_${scanData.targetHostname || 'target'}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' },
      pagebreak: { mode: ['css', 'legacy'] }
    };
    html2pdf().set(opt).from(container).save();
  };"""

content = re.sub(
    r"  const handleExportPdf = \(\) => \{[\s\S]*?html2pdf\(\)\.set\(opt\)\.from\(container\)\.save\(\);\n  \};",
    new_handle_export_pdf.strip(),
    content
)

with open('client/src/pages/Report.jsx', 'w', encoding='utf-8') as f:
    f.write(content)

print("Report.jsx updated with MASSIVE PDF export!")
