const express = require('express');
const router = express.Router();
const { Octokit } = require('@octokit/rest');

// POST /api/github/create-pr
// Requires: repoUrl, patToken, fixData (filePath, replacementCode)
router.post('/create-pr', async (req, res) => {
    try {
        const { repoUrl, patToken, fixData } = req.body;

        if (!repoUrl || !patToken || !fixData || !fixData.filePath || !fixData.replacementCode) {
            return res.status(400).json({ error: 'Missing required parameters' });
        }

        // Parse owner and repo from URL
        let urlParts;
        try {
            urlParts = new URL(repoUrl);
        } catch (e) {
            return res.status(400).json({ error: 'Invalid GitHub URL format' });
        }

        const pathParts = urlParts.pathname.split('/').filter(p => p);

        if (pathParts.length < 2) {
            return res.status(400).json({ error: 'Invalid GitHub URL - Please provide a repository URL' });
        }

        const owner = pathParts[0];
        const repo = pathParts[1].replace('.git', '');

        const octokit = new Octokit({
            auth: patToken
        });

        // 1. Get default branch 
        const { data: repoData } = await octokit.rest.repos.get({
            owner,
            repo,
        });
        const defaultBranch = repoData.default_branch;

        // 2. Get the SHA of the default branch's latest commit
        const { data: refData } = await octokit.rest.git.getRef({
            owner,
            repo,
            ref: `heads/${defaultBranch}`,
        });
        const baseCommitSha = refData.object.sha;

        // 3. Create a unique branch name for the fix
        const timestamp = Date.now();
        const branchName = `secura-fix-${timestamp}`;

        await octokit.rest.git.createRef({
            owner,
            repo,
            ref: `refs/heads/${branchName}`,
            sha: baseCommitSha,
        });

        // 4. Fetch the existing file content to get its SHA
        let fileSha;
        try {
            const { data: fileData } = await octokit.rest.repos.getContent({
                owner,
                repo,
                path: fixData.filePath,
                ref: branchName
            });
            if (Array.isArray(fileData)) {
                return res.status(400).json({ error: 'Provided path is a directory, not a file' });
            }
            fileSha = fileData.sha;
        } catch (error) {
            // Normal if the file doesn't exist
            if (error.status !== 404) {
                throw error;
            }
        }

        // 5. Commit the new replacement code
        const message = `Secura AI: Security Fix for ${fixData.filePath}`;
        await octokit.rest.repos.createOrUpdateFileContents({
            owner,
            repo,
            path: fixData.filePath,
            message,
            content: Buffer.from(fixData.replacementCode).toString('base64'),
            branch: branchName,
            sha: fileSha
        });

        // 6. Create the Pull Request
        const { data: prData } = await octokit.rest.pulls.create({
            owner,
            repo,
            title: message,
            head: branchName,
            base: defaultBranch,
            body: 'This PR was automatically generated by Secura AI to resolve a detected security vulnerability.\n\n**Please review the changes before merging.**',
        });

        return res.json({ success: true, prUrl: prData.html_url });

    } catch (error) {
        console.error('Error creating PR:', error);
        return res.status(500).json({
            error: 'Failed to create GitHub PR',
            message: error.message || 'An error occurred during PR generation'
        });
    }
});

module.exports = router;
